{% set name = "bibmanager" %}
{% set version = "1.4.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bibmanager-{{ version }}.tar.gz
  sha256: e2f445a72c1bb48860d97dd7a27d39e9fc96dc2f361bd43c738d9ce69d068e83

build:
  number: 0
  noarch: python
  entry_points:
    - bibm = bibmanager.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.15.1
    - packaging >=17.1
    - prompt-toolkit >=3.0.5
    - pygments >=2.2.0
    - python >=3.6
    - requests >=2.19.1

test:
  imports:
    - bibmanager

about:
  home: https://github.com/pcubillos/bibmanager
  summary: A BibTeX manager for LaTeX projects
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pcubillos/bibmanager
  doc_url: https://bibmanager.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - pcubillos
